[compiler.solc]
remappings = [
    "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts/contracts/",
    "@uniswap/lib/=contracts/lib/uniswap-lib/",
    "@uniswap/v2-core/=contracts/lib/uniswap-v2-core/",
    "@uniswap/v2-periphery/=contracts/lib/uniswap-v2-periphery/",
    "forge-std/=contracts/lib/forge-std/src/"
]
