import { expect,test,type Page } from "@playwright/test";

const fillMetadata=async(page:Page,suffix="One",withLinks=true)=>{await page.getByLabel("Token name").fill(`Launch ${suffix}`);await page.getByLabel("Symbol").fill(`NOX${suffix.length}`);await page.getByLabel("Description").fill("A lifecycle test launch with immutable fixed supply.");if(withLinks){await page.getByLabel("Image URL (optional)").fill("https://example.com/token.png");await page.getByLabel("Website (optional)").fill("https://example.com")}};

test("create without optional links or initial buy, then buy, sell, and claim",async({page})=>{await page.goto("/create?demo=1");await fillMetadata(page,"Zero",false);await page.getByRole("button",{name:"Create launch"}).click();await expect(page).toHaveURL(/\/token\/\d+/);await expect(page.getByText("Website ↗")).toHaveCount(0);await expect(page.getByText("Curve live").first()).toBeVisible();await page.getByLabel("Buy amount").fill("0.01");await page.getByRole("button",{name:/Buy on curve/}).click();await expect(page.getByText("Confirmed onchain").first()).toBeVisible();await page.getByRole("button",{name:"Sell",exact:true}).click();await page.getByLabel("Sell amount").fill("1");await page.getByRole("button",{name:/Sell on curve/}).click();await expect(page.getByText("Market activity")).toBeVisible();await page.getByRole("button",{name:"Claim"}).first().click();await expect(page.getByText("Confirmed onchain").first()).toBeVisible()});

test("create with capped initial buy opens atomically",async({page})=>{await page.goto("/create?demo=1");await fillMetadata(page,"Funded");await page.getByLabel("Initial purchase").fill("0.01");await expect(page.getByText("Expected tokens")).toBeVisible();await page.getByRole("button",{name:"Create launch"}).click();await expect(page).toHaveURL(/\/token\/\d+/);await expect(page.getByText("Curve live").first()).toBeVisible();await expect(page.getByText("Awaiting launch")).toHaveCount(0)});

test("final buy refund, graduation, and AMM mode",async({page})=>{await page.goto("/token/1?demo=1");await expect(page.getByText("Pending refund")).toBeVisible();await page.getByRole("button",{name:"Complete curve (demo)"}).click();await expect(page.getByText("AMM live").first()).toBeVisible();await expect(page.getByText("Guarded V2 AMM").first()).toBeVisible();await page.getByLabel("Buy amount").fill("0.01");await expect(page.getByRole("button",{name:"Buy on AMM"})).toBeEnabled();await page.getByRole("button",{name:"Claim"}).first().click();await expect(page.getByText("Confirmed onchain").first()).toBeVisible()});

test("metadata validation, keyboard access, responsive navigation, and hidden administration",async({page})=>{await page.goto("/create?demo=1");await page.getByRole("button",{name:"Create launch"}).focus();await page.keyboard.press("Enter");await expect(page.getByText("Use 1–32 characters.")).toBeVisible();await page.setViewportSize({width:390,height:844});const navigation=page.getByRole("navigation",{name:"Primary navigation"});await expect(navigation).toBeVisible();await expect(navigation.getByRole("link",{name:"Admin"})).toHaveCount(0);await page.goto("/admin?demo=1");await expect(page.getByRole("heading",{name:"Page not found"})).toBeVisible();await expect(page.getByLabel("Admin bearer token")).toHaveCount(0)});
